GET http://localhost:3000/api/status


###

GET http://localhost:3000/api/user/list

###

DELETE http://localhost:3000/api/user/delete?id=8

###

POST http://localhost:3000/api/user/sign
Content-Type: application/json

{
    "username": "jdaae",
    "email": "joahndoee@example.com",
    "name": "John Doe",
    "role": "it agent"
}

###

PUT http://localhost:3000/api/user/update
Content-Type: application/json

{
    "id": "11",
    "name": "Jane Doe",
    "email": "jaaohndoe1337@example.com"
}