GET http://localhost:3000/api/status

###

GET http://localhost:3000/api/user/list

###

GET http://localhost:3000/api/user/role/TI

###

DELETE http://localhost:3000/api/user/delete?id=6d6c8518-9214-4e10-a1b5-84ae6a11b285

###

POST http://localhost:3000/api/user/sign
Content-Type: application/json

{
    "username": "aaaa1a",
    "email": "jdoaaaaaa1Ae@a.com",
    "password": "123415678",
    "name": "John 1Doe",
    "role": "TI"
}

###

PUT http://localhost:3000/api/user/update
Content-Type: application/json

{
    "id": "157becad-05d6-4c15-85ab-127aa6082a86",
    "username": "jdoe2",
    "role": "TI"
    }

###

POST http://localhost:3000/api/newsletter/subscribe
Content-Type: application/json

{
  "email": "jdoe2@example.com"
}

###

GET http://localhost:3000/api/newsletter/list

###

DELETE http://localhost:3000/api/newsletter/unsubscribe
Content-Type: application/json

{
  "email": "johndoe@example.com"
}

###

POST http://localhost:3000/api/migrations

###

POST http://localhost:3000/api/newsletter/sendbulk
Content-Type: application/json

{
  "title": "TESTE",
  "description": "Isto é um teste",
  "body_text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In rhoncus blandit lectus eu luctus. Praesent ac posuere tellus. Mauris sagittis vitae orci vel tincidunt. Etiam ut arcu ac risus molestie mattis. Etiam a tellus dolor. Mauris eget efficitur ex. Aliquam condimentum ac nulla non varius.",
  "owner_id": "1",
  "imageURL": "..."
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "admin@gpda.com.br",
    "password": "admin"
}