GET http://localhost:3000/api/status


###

GET http://localhost:3000/api/user/list

###

GET http://localhost:3000/api/user/role/TI

###

DELETE http://localhost:3000/api/user/delete?id=2

###

POST http://localhost:3000/api/user/sign
Content-Type: application/json

{
    "username": "jadoe",
    "email": "janedoe@example.com",
    "name": "Jane Doe",
    "role": "TI"
}

###

PUT http://localhost:3000/api/user/update
Content-Type: application/json

{
    "id": "2",
    "username": "jdoe"
}

###

POST http://localhost:3000/api/newsletter/sign

{
  "email": "jdoe@example.com"
}